apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ollama
  name: ollama
  namespace: ollama
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - image: ollama/ollama:latest
          name: ollama
          ports:
            - containerPort: 11434
          resources:
            requests:
              cpu: 2000m
              memory: 4Gi
            limits:
                cpu: 4000m
                memory: 8Gi
        - image: curlimages/curl
          name: load-model
          command: ["/bin/sh", "-c"]
          args:
            - "sleep infinity"
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "curl -X POST http://localhost:11434/api/pull -H 'Content-Type: application/json' -d '{\"name\": \"llama3.2\"}'"
          resources:
            limits:
              memory: 50Mi
              cpu: 25m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollama
  name: ollama
  namespace: ollama
spec:
  selector:
    app: ollama
  ports:
    - port: 11434


# kubectl port-forward --namespace ollama service/ollama 11434:11434
